import { type NextPage } from "next";
import Head from "next/head";
import type { ChangeEventHandler, Dispatch, SetStateAction} from "react";
import { useState } from "react";

type HandleUpdateFunc = (fn: Dispatch<SetStateAction<string>>) => ChangeEventHandler<HTMLInputElement>

const Home: NextPage = () => {
  const [program, setProgram] = useState('/usr/local/bin/grafana-agent');
  const [description, setDescription] = useState('Run Grafana Agent');

  const handleUpdate: HandleUpdateFunc = (fn) => (ev) => {
    fn(ev.target.value);
  };

  const unit = `[Unit]
Description=${description}

[Service]
Type=simple
ExecStart=${program}

[Install]
WantedBy=multi-user.target`;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto bg-gray-50">
        <h1 className="font-bold text-3xl text-center py-6">Simple Service Generator</h1>
        <div className="flex">
          <div className="w-full p-6 flex flex-col gap-6">
            <fieldset className="flex flex-col gap-3">
              <label>Program to run</label>
              <input
                className="bg-white border px-2 py-1 focus:outline-none focus:border-blue-500"
                type="text"
                placeholder="/usr/local/bin/program -s 1"
                onChange={handleUpdate(setProgram)}
                />
              <p className="text-sm text-gray-500">This must be the path to a program or script you want to run.</p>
            </fieldset>

            <fieldset className="flex flex-col gap-3">
              <label>Description</label>
              <input
                className="bg-white border px-2 py-1 focus:outline-none focus:border-blue-500"
                type="text"
                placeholder="Runs the program with a 1 second second."
                onChange={handleUpdate(setDescription)}
                />
            </fieldset>
          </div>

          <div className="w-full p-6">
            <div className="bg-gray-300 h-10 flex items-center px-4">/etc/systemd/system/&lt;name&gt;.service</div>
            <pre className="bg-gray-100 w-full p-4 flex flex-col gap-1 text-sm">
              {unit.split('\n').map((v, i) => (
                <p key={i} className="h-5">{v}</p>
              ))}
            </pre>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

